/* eslint-disable no-param-reassign */
// Import createSlice() from Redux toolkit:
import { createSlice } from '@reduxjs/toolkit';

// Initial state for Redux store:
const initialState = {
  books: [],
};

// Create Redux state slice
const bookslice = createSlice({
  name: 'books',
  initialState, // Define initial state
  reducers: {
    // Define reducers
    loadBooks: (state, action) => {
      state.books = [...state.books, action.payload];
    },
    addBook: (state, action) => {
      state.books = [...state.books, action.payload];
    },
    removeBook: (state, action) => {
      state.books = state.books.filter((book) => book.id !== action.payload.id);
    },
  },
});

// Export actions generated by "createSlice()":
export const { addBook, removeBook, loadBooks } = bookslice.actions;

// Export reducer generated by "createSlice()":
export default bookslice.reducer;
